name: Tests

on:
  push:
  pull_request:

jobs:
  quality:
    name: Code quality checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linter
        run: |
          cd src
          deno lint

      - name: Check Formatting
        run: |
          cd src
          deno fmt --check

      - name: Run tests
        run: deno test --allow-net --allow-env

  bundle:
    name: Bundle
    needs: quality
    if: contains(github.ref, 'main')
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: releases

      - name: Pull from main
        run: |
          git fetch origin main
          git reset --hard FETCH_HEAD
          git clean -df

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # esbuild is node based
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install esbuild
        run: npm install esbuild -g

      - name: Run bundler
        run: deno bundle src/cla-functions/cli.ts | esbuild --minify > actions/cla/bundle.js
      
      - uses: EndBug/add-and-commit@v7
        with:
          branch: releases
          default_author: github_actions
          message: Automated bundle
          push: -f
          pull_strategy: 'NO-PULL'
